spring.application.name=uspsaMatchParser
spring.datasource.url=jdbc:postgresql://localhost:5432/scores
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
